version: "3"
services:
  app: &app
    build:
      context: .
      dockerfile: ./Dockerfile
    tty: true
    ports:
      - "5000:5000"
    container_name: app
    volumes:
      - type: bind
        source: app
        target: /work/app
    env_file:
      - .env
    depends_on:
      - db
    command: python3 app.py
  tailwind:
    container_name: tailwind
    <<: *app
    command: npm run build-css
    ports: []
  db:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: database
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      TZ: 'Asia/Tokyo'
    ports:
      - '5432:5432'
    volumes:
      - type: bind
        source: db
        target: /var/lib/postgresql/data
    env_file:
      - .env
